### ISSUE TITLE
ISO 22057 - EPD type: manufacturer representation & product representation

### ISSUE THREAD

**Issue by RobertSpang** [InDataWG/ILCD-EPD-Data-Format#29] opened 2024-02-08 15:34 UTC
### I raise this change request because...

- [ ] the ILCD+EPD format lacks compliance with regualtions.
- [X] the ILCD+EPD format lacks conformaty with standards.
- [ ] the ILCD+EPD format needs to be improved regarding existing format or master data elements.
- [ ] there is another problem or use case I´m trying to address.

### Problem description

This issue actually tackles two issues:
- manufacturer representation --> valid for a single manufacturing site; valid for several manufacturing sites from the same company with variation below 10 %; valid for several manufacturing sites from the same company with variation above 10 %; valid for several companies’ sites with variation below 10 %; valid for several companies’ sites with variation above 10 %.

- product representation --> valid for a single product where variability is not described; valid for a single product where variability is described; valid for a range of products where variability is not described; valid for a range of products where variability is not described

### Solution description

Check redundancy with existing B1.2 "subtype" in particular for "manufacturer representation" --> maybe extension possible?

"product representation" would be most likely a new element/field of the format --> guess the list from above will be further specified in the context of the CE mark

### Relevance or added value

medium

**Comment by RobertSpang** [comment] 2024-03-28 08:35
Ready for further processing; all relevant infomation is available

**Comment by okworx** [comment] 2024-05-28 13:48
duplicate of #17

**Closed** 2024-06-21 12:35 UTC
Labels: duplicate, format change request
